/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    leagues: League;
    leaguesseason: Leaguesseason;
    leaguesstandings: Leaguesstanding;
    matches: Match;
    teams: Team;
    players: Player;
    'metadata-types': MetadataType;
    countries: Country;
    coaches: Coach;
    rivals: Rival;
    'sync-metadata': SyncMetadatum;
    'player-sync-checkpoint': PlayerSyncCheckpoint;
    'validation-results': ValidationResult;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leagues: LeaguesSelect<false> | LeaguesSelect<true>;
    leaguesseason: LeaguesseasonSelect<false> | LeaguesseasonSelect<true>;
    leaguesstandings: LeaguesstandingsSelect<false> | LeaguesstandingsSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    'metadata-types': MetadataTypesSelect<false> | MetadataTypesSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    coaches: CoachesSelect<false> | CoachesSelect<true>;
    rivals: RivalsSelect<false> | RivalsSelect<true>;
    'sync-metadata': SyncMetadataSelect<false> | SyncMetadataSelect<true>;
    'player-sync-checkpoint': PlayerSyncCheckpointSelect<false> | PlayerSyncCheckpointSelect<true>;
    'validation-results': ValidationResultsSelect<false> | ValidationResultsSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      syncLeagues: TaskSyncLeagues;
      syncTeams: TaskSyncTeams;
      syncMatches: TaskSyncMatches;
      syncPlayers: TaskSyncPlayers;
      syncMetadataTypes: TaskSyncMetadataTypes;
      syncCountries: TaskSyncCountries;
      syncCoaches: TaskSyncCoaches;
      syncRivals: TaskSyncRivals;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leagues".
 */
export interface League {
  id: number;
  name: string;
  logo_path?: string | null;
  country_id: number;
  league_type: string;
  stages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  latest?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  upcoming?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  inplay?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  today?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  currentseason?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Display priority in match listings (higher numbers appear first, 0 = default order)
   */
  priority?: number | null;
  /**
   * League tier for automatic prioritization
   */
  tier?: ('tier1' | 'tier2' | 'tier3' | 'tier4') | null;
  /**
   * Feature this league prominently in match listings
   */
  featured?: boolean | null;
  current_standings?: {
    /**
     * Cached league table calculated from match results
     */
    table?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Season ID this table is for
     */
    season_id?: number | null;
    /**
     * When this table was last calculated
     */
    last_calculated?: string | null;
    /**
     * When this cache expires (default: 6 hours)
     */
    expires_at?: string | null;
    /**
     * Number of teams in this league table
     */
    total_teams?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leaguesseason".
 */
export interface Leaguesseason {
  id: string;
  leagueId: number;
  seasons?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leaguesstandings".
 */
export interface Leaguesstanding {
  id: string;
  leagueId: number;
  standings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: number;
  sport_id: number;
  league_id: number | League;
  season_id: number;
  stage_id: number;
  state_id: number;
  starting_at: string;
  participants?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  scores?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  venue?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  state?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  league?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  season?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  stage?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  round?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  group?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  aggregate?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  statistics?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  events?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  periods?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lineups?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sidelined?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  coaches?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  weatherreport?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  wave_score?: {
    /**
     * Total wave score (0-100)
     */
    total?: number | null;
    /**
     * Wave score tier classification
     */
    tier?: ('S' | 'A' | 'B' | 'C') | null;
    factors?: {
      /**
       * Rivalry factor score (0-30)
       */
      rivalry?: number | null;
      /**
       * Position proximity score (0-20)
       */
      position?: number | null;
      /**
       * Zone importance score (0-20)
       */
      zone?: number | null;
      /**
       * Form differential score (0-15)
       */
      form?: number | null;
      /**
       * Head-to-head drama score (0-10)
       */
      h2h?: number | null;
      /**
       * Timing bonus score (0-5)
       */
      timing?: number | null;
    };
    /**
     * When the wave score was calculated
     */
    calculated_at?: string | null;
    /**
     * When the wave score expires (typically match start time)
     */
    expires_at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  name: string;
  logo_path?: string | null;
  country_id?: number | null;
  coaches?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  players?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  latest?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  upcoming?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  seasons?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  activeseasons?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  statistics?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  trophies?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  socials?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rankings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  standings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  season_map?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  sport_id: number;
  country_id?: number | null;
  nationality_id?: number | null;
  position_id?: number | null;
  detailed_position_id?: number | null;
  name: string;
  common_name?: string | null;
  firstname?: string | null;
  lastname?: string | null;
  display_name?: string | null;
  image_path?: string | null;
  height?: number | null;
  weight?: number | null;
  date_of_birth?: string | null;
  gender?: string | null;
  teams?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  statistics?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lineups?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  transfers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pendingtransfers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  trophies?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  latest?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  nationality?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metadata-types".
 */
export interface MetadataType {
  id: number;
  parent_id?: number | null;
  name: string;
  code: string;
  developer_name?: string | null;
  group?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  continent_id: number;
  name: string;
  official_name?: string | null;
  fifa_name?: string | null;
  iso2?: string | null;
  iso3?: string | null;
  latitude?: string | null;
  longitude?: string | null;
  geonameid?: number | null;
  borders?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  image_path?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches".
 */
export interface Coach {
  id: number;
  /**
   * Unique ID from Sportmonks
   */
  sportmonksId: string;
  name: string;
  firstName?: string | null;
  lastName?: string | null;
  dateOfBirth?: string | null;
  gender?: ('male' | 'female') | null;
  /**
   * Image URL from Sportmonks
   */
  image?: string | null;
  country?: (number | null) | Country;
  nationality?: (number | null) | Country;
  /**
   * Teams this coach has managed
   */
  teams?:
    | {
        teamId: number | Team;
        active?: boolean | null;
        startDate?: string | null;
        endDate?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * When this record was last updated
   */
  lastUpdated?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rivals".
 */
export interface Rival {
  id: number;
  team_id: number;
  rival_team_id: number;
  team?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rival?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  h2h_summary?: {
    total_matches?: number | null;
    last_5?: {
      team_wins?: number | null;
      rival_wins?: number | null;
      draws?: number | null;
    };
    overall?: {
      team_wins?: number | null;
      rival_wins?: number | null;
      draws?: number | null;
    };
    last_meeting?: {
      date?: string | null;
      result?: string | null;
      score?: string | null;
      venue_id?: number | null;
    };
    drama_score?: number | null;
    avg_goals_per_match?: number | null;
  };
  h2h_updated_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-metadata".
 */
export interface SyncMetadatum {
  id: string;
  /**
   * Unique identifier for the sync operation (e.g., "rivals_data", "h2h_data")
   */
  syncType: string;
  /**
   * Timestamp of the last successful sync
   */
  lastSyncAt: string;
  /**
   * Time-to-live in days before next sync is allowed
   */
  ttlDays: number;
  /**
   * Human-readable description of what this sync does
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-sync-checkpoint".
 */
export interface PlayerSyncCheckpoint {
  id: string;
  /**
   * Unique identifier for this sync process
   */
  syncId: string;
  /**
   * Current page being processed
   */
  currentPage: number;
  /**
   * Total pages discovered from API pagination info
   */
  totalPagesDiscovered?: number | null;
  /**
   * Total number of players processed so far
   */
  playersProcessed: number;
  /**
   * When this checkpoint was last updated
   */
  lastSyncTime: string;
  /**
   * When the current sync cycle started
   */
  syncStartTime?: string | null;
  /**
   * Current state of the sync process
   */
  mode: 'fresh-start' | 'resuming' | 'completed' | 'rate-limited' | 'failed';
  rateLimit?: {
    /**
     * API calls used in current hour
     */
    callsUsed?: number | null;
    /**
     * When rate limit resets
     */
    resetTime?: string | null;
    /**
     * Timestamp of last API call
     */
    lastCallTime?: string | null;
  };
  stats?: {
    playersCreated?: number | null;
    playersUpdated?: number | null;
    playersFailed?: number | null;
    pagesCompleted?: number | null;
  };
  /**
   * Last error message if sync failed
   */
  lastError?: string | null;
  /**
   * Calculated time when sync can resume after rate limit
   */
  nextResumeTime?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "validation-results".
 */
export interface ValidationResult {
  id: string;
  jobType: 'syncTeams' | 'syncPlayers' | 'syncMatches' | 'syncLeagues' | 'manual';
  /**
   * Team ID that was validated (if applicable)
   */
  teamId?: number | null;
  teamName?: string | null;
  entity: 'fixtures' | 'teams' | 'players' | 'standings' | 'playerstats';
  status: 'pass' | 'fail' | 'error' | 'pending';
  totalDiscrepancies?: number | null;
  /**
   * Summary of comparison results
   */
  comparisonSummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Detailed discrepancy data
   */
  discrepancies?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Recommended sync jobs to fix discrepancies
   */
  syncRecommendations?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Error message if validation failed
   */
  error?: string | null;
  /**
   * Validation execution time in milliseconds
   */
  executionTime?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'syncLeagues'
          | 'syncTeams'
          | 'syncMatches'
          | 'syncPlayers'
          | 'syncMetadataTypes'
          | 'syncCountries'
          | 'syncCoaches'
          | 'syncRivals';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'syncLeagues'
        | 'syncTeams'
        | 'syncMatches'
        | 'syncPlayers'
        | 'syncMetadataTypes'
        | 'syncCountries'
        | 'syncCoaches'
        | 'syncRivals'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'leagues';
        value: number | League;
      } | null)
    | ({
        relationTo: 'leaguesseason';
        value: string | Leaguesseason;
      } | null)
    | ({
        relationTo: 'leaguesstandings';
        value: string | Leaguesstanding;
      } | null)
    | ({
        relationTo: 'matches';
        value: number | Match;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'metadata-types';
        value: number | MetadataType;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'coaches';
        value: number | Coach;
      } | null)
    | ({
        relationTo: 'rivals';
        value: number | Rival;
      } | null)
    | ({
        relationTo: 'sync-metadata';
        value: string | SyncMetadatum;
      } | null)
    | ({
        relationTo: 'player-sync-checkpoint';
        value: string | PlayerSyncCheckpoint;
      } | null)
    | ({
        relationTo: 'validation-results';
        value: string | ValidationResult;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: string | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leagues_select".
 */
export interface LeaguesSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  logo_path?: T;
  country_id?: T;
  league_type?: T;
  stages?: T;
  latest?: T;
  upcoming?: T;
  inplay?: T;
  today?: T;
  currentseason?: T;
  priority?: T;
  tier?: T;
  featured?: T;
  current_standings?:
    | T
    | {
        table?: T;
        season_id?: T;
        last_calculated?: T;
        expires_at?: T;
        total_teams?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leaguesseason_select".
 */
export interface LeaguesseasonSelect<T extends boolean = true> {
  leagueId?: T;
  seasons?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leaguesstandings_select".
 */
export interface LeaguesstandingsSelect<T extends boolean = true> {
  leagueId?: T;
  standings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  id?: T;
  sport_id?: T;
  league_id?: T;
  season_id?: T;
  stage_id?: T;
  state_id?: T;
  starting_at?: T;
  participants?: T;
  scores?: T;
  venue?: T;
  state?: T;
  league?: T;
  season?: T;
  stage?: T;
  round?: T;
  group?: T;
  aggregate?: T;
  statistics?: T;
  events?: T;
  periods?: T;
  lineups?: T;
  sidelined?: T;
  coaches?: T;
  metadata?: T;
  weatherreport?: T;
  wave_score?:
    | T
    | {
        total?: T;
        tier?: T;
        factors?:
          | T
          | {
              rivalry?: T;
              position?: T;
              zone?: T;
              form?: T;
              h2h?: T;
              timing?: T;
            };
        calculated_at?: T;
        expires_at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  logo_path?: T;
  country_id?: T;
  coaches?: T;
  players?: T;
  latest?: T;
  upcoming?: T;
  seasons?: T;
  activeseasons?: T;
  statistics?: T;
  trophies?: T;
  socials?: T;
  rankings?: T;
  standings?: T;
  season_map?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  id?: T;
  sport_id?: T;
  country_id?: T;
  nationality_id?: T;
  position_id?: T;
  detailed_position_id?: T;
  name?: T;
  common_name?: T;
  firstname?: T;
  lastname?: T;
  display_name?: T;
  image_path?: T;
  height?: T;
  weight?: T;
  date_of_birth?: T;
  gender?: T;
  teams?: T;
  statistics?: T;
  lineups?: T;
  transfers?: T;
  pendingtransfers?: T;
  trophies?: T;
  latest?: T;
  metadata?: T;
  nationality?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metadata-types_select".
 */
export interface MetadataTypesSelect<T extends boolean = true> {
  id?: T;
  parent_id?: T;
  name?: T;
  code?: T;
  developer_name?: T;
  group?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  id?: T;
  continent_id?: T;
  name?: T;
  official_name?: T;
  fifa_name?: T;
  iso2?: T;
  iso3?: T;
  latitude?: T;
  longitude?: T;
  geonameid?: T;
  borders?: T;
  image_path?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches_select".
 */
export interface CoachesSelect<T extends boolean = true> {
  id?: T;
  sportmonksId?: T;
  name?: T;
  firstName?: T;
  lastName?: T;
  dateOfBirth?: T;
  gender?: T;
  image?: T;
  country?: T;
  nationality?: T;
  teams?:
    | T
    | {
        teamId?: T;
        active?: T;
        startDate?: T;
        endDate?: T;
        id?: T;
      };
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rivals_select".
 */
export interface RivalsSelect<T extends boolean = true> {
  id?: T;
  team_id?: T;
  rival_team_id?: T;
  team?: T;
  rival?: T;
  h2h_summary?:
    | T
    | {
        total_matches?: T;
        last_5?:
          | T
          | {
              team_wins?: T;
              rival_wins?: T;
              draws?: T;
            };
        overall?:
          | T
          | {
              team_wins?: T;
              rival_wins?: T;
              draws?: T;
            };
        last_meeting?:
          | T
          | {
              date?: T;
              result?: T;
              score?: T;
              venue_id?: T;
            };
        drama_score?: T;
        avg_goals_per_match?: T;
      };
  h2h_updated_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-metadata_select".
 */
export interface SyncMetadataSelect<T extends boolean = true> {
  syncType?: T;
  lastSyncAt?: T;
  ttlDays?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-sync-checkpoint_select".
 */
export interface PlayerSyncCheckpointSelect<T extends boolean = true> {
  syncId?: T;
  currentPage?: T;
  totalPagesDiscovered?: T;
  playersProcessed?: T;
  lastSyncTime?: T;
  syncStartTime?: T;
  mode?: T;
  rateLimit?:
    | T
    | {
        callsUsed?: T;
        resetTime?: T;
        lastCallTime?: T;
      };
  stats?:
    | T
    | {
        playersCreated?: T;
        playersUpdated?: T;
        playersFailed?: T;
        pagesCompleted?: T;
      };
  lastError?: T;
  nextResumeTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "validation-results_select".
 */
export interface ValidationResultsSelect<T extends boolean = true> {
  jobType?: T;
  teamId?: T;
  teamName?: T;
  entity?: T;
  status?: T;
  totalDiscrepancies?: T;
  comparisonSummary?: T;
  discrepancies?: T;
  syncRecommendations?: T;
  error?: T;
  executionTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncLeagues".
 */
export interface TaskSyncLeagues {
  input?: unknown;
  output: {
    message?: string | null;
    stats?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncTeams".
 */
export interface TaskSyncTeams {
  input?: unknown;
  output: {
    message?: string | null;
    stats?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncMatches".
 */
export interface TaskSyncMatches {
  input: {
    startDate?: string | null;
    endDate?: string | null;
    backfill?: boolean | null;
  };
  output: {
    message?: string | null;
    stats?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncPlayers".
 */
export interface TaskSyncPlayers {
  input?: unknown;
  output: {
    message?: string | null;
    stats?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncMetadataTypes".
 */
export interface TaskSyncMetadataTypes {
  input?: unknown;
  output: {
    message?: string | null;
    stats?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncCountries".
 */
export interface TaskSyncCountries {
  input?: unknown;
  output: {
    message?: string | null;
    stats?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncCoaches".
 */
export interface TaskSyncCoaches {
  input?: unknown;
  output: {
    message?: string | null;
    stats?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncRivals".
 */
export interface TaskSyncRivals {
  input?: unknown;
  output: {
    message?: string | null;
    stats?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}